from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime
import os

def generate_issue_pdf(issue: dict, file_path: str):
    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    y = height - 50

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "NagarNetra – Municipal Issue Report")
    y -= 25

    c.setFont("Helvetica", 10)
    c.drawString(50, y, f"Generated on: {datetime.utcnow().strftime('%d %b %Y, %H:%M UTC')}")
    y -= 40

    # Issue details
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Issue Details")
    y -= 20

    c.setFont("Helvetica", 10)
    fields = [
        ("Issue ID", issue.get("id")),
        ("Issue Type", issue.get("issueType")),
        ("Department", issue.get("department")),
        ("Status", issue.get("status")),
        ("Severity", f"{issue.get('severity')}/10"),
        ("Votes", issue.get("votes")),
        ("Latitude", issue.get("latitude")),
        ("Longitude", issue.get("longitude")),
    ]

    for label, value in fields:
        c.drawString(60, y, f"{label}: {value}")
        y -= 15

    y -= 15

    # AI Analysis
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "AI Analysis")
    y -= 20

    c.setFont("Helvetica", 10)
    text = c.beginText(60, y)
    analysis = issue.get("aiAnalysis", "No AI analysis available.")
    for line in analysis.split("\n"):
        text.textLine(line)
    c.drawText(text)

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(
        50,
        30,
        "Generated by NagarNetra • AI-Powered Civic Governance System",
    )

    c.showPage()
    c.save()
